import type { z } from "zod";

import { AgentActionSchema, ApplicationCheckpointSchema, ApplicationSchema, ApprovalRequestSchema, FieldDecisionSchema, FieldObservationSchema } from "./application.js";
import { ArtifactSchema, AuditEventSchema } from "./audit.js";
import {
  BrowserActivateInputSchema,
  BrowserActivateOutputSchema,
  BrowserLivePageObservationSchema,
  BrowserMcpToolDescriptorSchema,
  BrowserNavigateInputSchema,
  BrowserNavigateOutputSchema,
  BrowserPageSnapshotSchema,
  BrowserRequestTakeoverInputSchema,
  BrowserRequestTakeoverOutputSchema,
  BrowserSessionOpenInputSchema,
  BrowserSessionOpenOutputSchema,
  BrowserSetFieldInputSchema,
  BrowserSetFieldOutputSchema,
  BrowserSetFileInputSchema,
  BrowserSetFileOutputSchema,
  BrowserSnapshotInputSchema,
  BrowserSnapshotOutputSchema,
  BrowserSubmitInputSchema,
  BrowserSubmitOutputSchema,
  BrowserTrustedAuthorizationRecordSchema,
  BrowserTrustedArtifactRecordSchema,
  BrowserTrustedEvidenceRecordSchema,
} from "./browser-mcp.js";
import { BrowserMcpWireToolSchema } from "./browser-mcp-wire.js";
import { BrowserWriteValidationContextSchema } from "./browser-mcp-validation.js";
import {
  ArtifactExportInputSchema,
  ArtifactExportOutputSchema,
  DocxApplyChangesetInputSchema,
  DocxApplyChangesetOutputSchema,
  DocxParseInputSchema,
  DocxParseOutputSchema,
  DocxPrivacyScrubInputSchema,
  DocxPrivacyScrubOutputSchema,
  DocxRenderPagesInputSchema,
  DocxRenderPagesOutputSchema,
  DocxStructureAuditInputSchema,
  DocxStructureAuditOutputSchema,
  DocxTextDiffInputSchema,
  DocxTextDiffOutputSchema,
  DocxVisualDiffInputSchema,
  DocxVisualDiffOutputSchema,
  DocumentBuildManifestSchema,
  DocumentContentBindingSchema,
  DocumentExportManifestSchema,
  DocumentMcpToolDescriptorSchema,
  DocumentPrivacyReportSchema,
  DocumentPresentationBindingSchema,
  DocumentPresentationItemSchema,
  DocumentPresentationPlanSchema,
  DocumentPresentationSourceSchema,
  DocumentQaReportSchema,
  DocumentRenderManifestSchema,
  DocumentSnapshotSchema,
  DocumentTemplateProfileSchema,
  DocumentTextDiffReportSchema,
  DocumentTrustedAuthorizationRecordSchema,
  DocumentVerifiedFactBindingSchema,
  DocumentVisualDiffReportSchema,
  TemplateInspectInputSchema,
  TemplateInspectOutputSchema,
} from "./document-mcp.js";
import {
  DocumentTrustedArtifactRecordSchema,
  DocumentTrustedComparatorRecordSchema,
  DocumentTrustedFactRecordSchema,
  DocumentTrustedInspectorRecordSchema,
  DocumentTrustedNonCreationEvidenceRecordSchema,
  DocumentTrustedParserRecordSchema,
  DocumentTrustedQaEvidenceRecordSchema,
  DocumentTrustedRendererRecordSchema,
  DocumentTrustedRequirementRecordSchema,
  DocumentTrustedResumeRecordSchema,
  DocumentTrustedTemplateRecordSchema,
  DocumentTrustedWorkerRecordSchema,
  DocumentValidationContextSchema,
} from "./document-mcp-validation.js";
import { DocumentMcpWireToolSchema } from "./document-mcp-wire.js";
import { JobSchema, JDRequirementSchema, RequirementFactMatchSchema } from "./job.js";
import {
  PolicyActionSchema,
  PolicyDecisionSchema,
  PolicyEvaluationInputSchema,
  PolicyFieldContextSchema,
  PolicyOriginContextSchema,
  PolicySafetySignalSchema,
} from "./policy.js";
import { AnswerPolicySchema, CandidateProfileSchema, FactSchema } from "./profile.js";
import { ResumeChangeReviewSchema, ResumeChangeSetSchema, ResumeContentApprovalSchema, ResumeIRSchema, ResumeVersionSchema } from "./resume.js";

export const schemaRegistry = {
  AnswerPolicy: AnswerPolicySchema,
  AgentAction: AgentActionSchema,
  Application: ApplicationSchema,
  ApplicationCheckpoint: ApplicationCheckpointSchema,
  ApprovalRequest: ApprovalRequestSchema,
  Artifact: ArtifactSchema,
  AuditEvent: AuditEventSchema,
  BrowserActivateInput: BrowserActivateInputSchema,
  BrowserActivateOutput: BrowserActivateOutputSchema,
  BrowserLivePageObservation: BrowserLivePageObservationSchema,
  BrowserMcpToolDescriptor: BrowserMcpToolDescriptorSchema,
  BrowserMcpWireTool: BrowserMcpWireToolSchema,
  BrowserNavigateInput: BrowserNavigateInputSchema,
  BrowserNavigateOutput: BrowserNavigateOutputSchema,
  BrowserPageSnapshot: BrowserPageSnapshotSchema,
  BrowserRequestTakeoverInput: BrowserRequestTakeoverInputSchema,
  BrowserRequestTakeoverOutput: BrowserRequestTakeoverOutputSchema,
  BrowserSessionOpenInput: BrowserSessionOpenInputSchema,
  BrowserSessionOpenOutput: BrowserSessionOpenOutputSchema,
  BrowserSetFieldInput: BrowserSetFieldInputSchema,
  BrowserSetFieldOutput: BrowserSetFieldOutputSchema,
  BrowserSetFileInput: BrowserSetFileInputSchema,
  BrowserSetFileOutput: BrowserSetFileOutputSchema,
  BrowserSnapshotInput: BrowserSnapshotInputSchema,
  BrowserSnapshotOutput: BrowserSnapshotOutputSchema,
  BrowserSubmitInput: BrowserSubmitInputSchema,
  BrowserSubmitOutput: BrowserSubmitOutputSchema,
  BrowserTrustedAuthorizationRecord: BrowserTrustedAuthorizationRecordSchema,
  BrowserTrustedArtifactRecord: BrowserTrustedArtifactRecordSchema,
  BrowserTrustedEvidenceRecord: BrowserTrustedEvidenceRecordSchema,
  BrowserWriteValidationContext: BrowserWriteValidationContextSchema,
  CandidateProfile: CandidateProfileSchema,
  ArtifactExportInput: ArtifactExportInputSchema,
  ArtifactExportOutput: ArtifactExportOutputSchema,
  DocumentBuildManifest: DocumentBuildManifestSchema,
  DocumentContentBinding: DocumentContentBindingSchema,
  DocumentExportManifest: DocumentExportManifestSchema,
  DocumentMcpToolDescriptor: DocumentMcpToolDescriptorSchema,
  DocumentMcpWireTool: DocumentMcpWireToolSchema,
  DocumentPrivacyReport: DocumentPrivacyReportSchema,
  DocumentPresentationBinding: DocumentPresentationBindingSchema,
  DocumentPresentationItem: DocumentPresentationItemSchema,
  DocumentPresentationPlan: DocumentPresentationPlanSchema,
  DocumentPresentationSource: DocumentPresentationSourceSchema,
  DocumentQaReport: DocumentQaReportSchema,
  DocumentRenderManifest: DocumentRenderManifestSchema,
  DocumentSnapshot: DocumentSnapshotSchema,
  DocumentTemplateProfile: DocumentTemplateProfileSchema,
  DocumentTextDiffReport: DocumentTextDiffReportSchema,
  DocumentTrustedArtifactRecord: DocumentTrustedArtifactRecordSchema,
  DocumentTrustedAuthorizationRecord: DocumentTrustedAuthorizationRecordSchema,
  DocumentTrustedComparatorRecord: DocumentTrustedComparatorRecordSchema,
  DocumentTrustedFactRecord: DocumentTrustedFactRecordSchema,
  DocumentTrustedInspectorRecord: DocumentTrustedInspectorRecordSchema,
  DocumentTrustedNonCreationEvidenceRecord: DocumentTrustedNonCreationEvidenceRecordSchema,
  DocumentTrustedParserRecord: DocumentTrustedParserRecordSchema,
  DocumentTrustedQaEvidenceRecord: DocumentTrustedQaEvidenceRecordSchema,
  DocumentTrustedRendererRecord: DocumentTrustedRendererRecordSchema,
  DocumentTrustedRequirementRecord: DocumentTrustedRequirementRecordSchema,
  DocumentTrustedResumeRecord: DocumentTrustedResumeRecordSchema,
  DocumentTrustedTemplateRecord: DocumentTrustedTemplateRecordSchema,
  DocumentTrustedWorkerRecord: DocumentTrustedWorkerRecordSchema,
  DocumentVerifiedFactBinding: DocumentVerifiedFactBindingSchema,
  DocumentValidationContext: DocumentValidationContextSchema,
  DocumentVisualDiffReport: DocumentVisualDiffReportSchema,
  DocxApplyChangesetInput: DocxApplyChangesetInputSchema,
  DocxApplyChangesetOutput: DocxApplyChangesetOutputSchema,
  DocxParseInput: DocxParseInputSchema,
  DocxParseOutput: DocxParseOutputSchema,
  DocxPrivacyScrubInput: DocxPrivacyScrubInputSchema,
  DocxPrivacyScrubOutput: DocxPrivacyScrubOutputSchema,
  DocxRenderPagesInput: DocxRenderPagesInputSchema,
  DocxRenderPagesOutput: DocxRenderPagesOutputSchema,
  DocxStructureAuditInput: DocxStructureAuditInputSchema,
  DocxStructureAuditOutput: DocxStructureAuditOutputSchema,
  DocxTextDiffInput: DocxTextDiffInputSchema,
  DocxTextDiffOutput: DocxTextDiffOutputSchema,
  DocxVisualDiffInput: DocxVisualDiffInputSchema,
  DocxVisualDiffOutput: DocxVisualDiffOutputSchema,
  Fact: FactSchema,
  FieldDecision: FieldDecisionSchema,
  FieldObservation: FieldObservationSchema,
  JDRequirement: JDRequirementSchema,
  Job: JobSchema,
  PolicyAction: PolicyActionSchema,
  PolicyDecision: PolicyDecisionSchema,
  PolicyEvaluationInput: PolicyEvaluationInputSchema,
  PolicyFieldContext: PolicyFieldContextSchema,
  PolicyOriginContext: PolicyOriginContextSchema,
  PolicySafetySignal: PolicySafetySignalSchema,
  RequirementFactMatch: RequirementFactMatchSchema,
  ResumeChangeReview: ResumeChangeReviewSchema,
  ResumeChangeSet: ResumeChangeSetSchema,
  ResumeContentApproval: ResumeContentApprovalSchema,
  ResumeIR: ResumeIRSchema,
  ResumeVersion: ResumeVersionSchema,
  TemplateInspectInput: TemplateInspectInputSchema,
  TemplateInspectOutput: TemplateInspectOutputSchema,
} satisfies Record<string, z.ZodType>;

export type SchemaName = keyof typeof schemaRegistry;
